#include "docc/cmd_args.h"

#include <sstream>

namespace docc {

llvm::cl::opt<std::string> DOCC_ROOT(
    "docc-root",
    llvm::cl::desc("Root of DOCC. Can be CMake:[path-to-cmake-build-dir] or Dist:[path-to-docc-dist-dir]"),
    llvm::cl::init("None")
);

llvm::cl::opt<std::string> DOCC_TUNE(
    "docc-tune",
    llvm::cl::desc("Enables DOCC tuning mode"),
    llvm::cl::init("none"),
    llvm::cl::value_desc("none|openmp|sequential|cuda|tenstorrent|rocm")
);

llvm::cl::opt<std::string> DOCC_WORK_DIR(
    "docc-work-dir", llvm::cl::desc("Sets the directory DOCC will output intermediate files to"), llvm::cl::init("")
);

llvm::cl::opt<bool> DOCC_FORCE_SYNCHRONOUS_OFFLOADING(
    "docc-offloading-force-synchronous",
    llvm::cl::init(false),
    llvm::cl::desc("Force all parts of offloading possible to be synchronous (slower, but easier "
                   "to debug and to see the time it takes")
);

llvm::cl::opt<bool> DOCC_SAVE_TEMPS(
    "docc-save-temps", llvm::cl::desc("Do not clean up intermediary files / create more"), llvm::cl::init(false)
);

bool DOCC_DUMP_GLBL_CFG_EN = false;
llvm::cl::opt<std::string> DOCC_DUMP_GLBL_CFG(
    "docc-dump-glbl-cfg",
    llvm::cl::desc("Path to dump global cfgs"),
    llvm::cl::ValueOptional,
    llvm::cl::callback([](const std::string &Val) { DOCC_DUMP_GLBL_CFG_EN = true; })
);

llvm::cl::list<std::string, bool>
    DOCC_COMP_OPTS("docc-comp-opt", llvm::cl::desc("Sets compile options for the code generated by DOCC"));

llvm::cl::opt<bool>
    DOCC_TRANSFERTUNE("docc-transfer-tune", llvm::cl::desc("Enables transfer-tuning"), llvm::cl::init(false));

llvm::cl::opt<std::string> DOCC_TRANSFERTUNE_CATEGORY(
    "docc-target-architecture",
    llvm::cl::desc("Sets the target architecture category for transfer tuning"),
    llvm::cl::init("server"),
    llvm::cl::value_desc("server")
);

llvm::cl::opt<std::string> DOCC_FUNC_BLACKLIST(
    "docc-func-blacklist", llvm::cl::desc("regex for functions that may not be lifted by DOCC"), llvm::cl::init("")
);

llvm::cl::opt<bool> DOCC_OFFLOAD_UNKNOWN_SIZES(
    "docc-offload-unknown-sizes",
    llvm::cl::desc("Enables offloading of unknown sizes, using malloc_usable_size() as an overestimation"),
    llvm::cl::init(false)
);

namespace args {

llvm::cl::opt<bool> DOCC_DOT_DUMP_SCHEDULED(
    "docc-dot-scheduled", llvm::cl::desc("Dumps the scheduled graph to a DOT file"), llvm::cl::init(false)
);

llvm::cl::opt<std::string> DOCC_LINK_MODE(
    "docc-link", llvm::cl::desc("Sets special options for how to link. Experimental"), llvm::cl::init("")
);

llvm::cl::opt<bool> DOCC_NO_OFFLOADING_TRANSFER_OPT(
    "docc-no-offloading-transfer-opt",
    llvm::cl::desc("Disables offloading transfer optimization"),
    llvm::cl::init(false)
);

std::string collect_subcompile_override_flags() {
    if (DOCC_COMP_OPTS.empty()) {
        return {};
    } else {
        std::ostringstream buf;

        for (const auto &item : DOCC_COMP_OPTS) {
            buf << item << " ";
        }
        return buf.str();
    }
}

} // namespace args
} // namespace docc
