#include "docc/lifting/functions/function_lifting.h"

#include <sdfg/data_flow/library_nodes/math/math.h>

namespace docc {
namespace lifting {

class IntrinsicLifting : public FunctionLifting {
private:
    static bool is_noop(llvm::Intrinsic::ID iid) {
        switch (iid) {
            case llvm::Intrinsic::annotation:
            case llvm::Intrinsic::assume:
            case llvm::Intrinsic::dbg_assign:
            case llvm::Intrinsic::dbg_declare:
            case llvm::Intrinsic::dbg_label:
            case llvm::Intrinsic::dbg_value:
            case llvm::Intrinsic::donothing:
            case llvm::Intrinsic::experimental_noalias_scope_decl:
            case llvm::Intrinsic::invariant_end:
            case llvm::Intrinsic::invariant_start:
            case llvm::Intrinsic::lifetime_end:
            case llvm::Intrinsic::lifetime_start:
            case llvm::Intrinsic::ptr_annotation:
            case llvm::Intrinsic::var_annotation:
                return true;
            default:
                return false;
        }
    }

    static bool is_tasklet(llvm::Intrinsic::ID iid) {
        switch (iid) {
            case llvm::Intrinsic::expect:
            case llvm::Intrinsic::expect_with_probability:
            case llvm::Intrinsic::abs:
            case llvm::Intrinsic::smax:
            case llvm::Intrinsic::smin:
            case llvm::Intrinsic::scmp:
            case llvm::Intrinsic::umax:
            case llvm::Intrinsic::umin:
            case llvm::Intrinsic::ucmp:
            case llvm::Intrinsic::fmuladd:
                return true;
            default:
                return false;
        }
    }

    static sdfg::data_flow::TaskletCode as_tasklet(llvm::Intrinsic::ID iid) {
        switch (iid) {
            case llvm::Intrinsic::expect:
                return sdfg::data_flow::TaskletCode::assign;
            case llvm::Intrinsic::expect_with_probability:
                return sdfg::data_flow::TaskletCode::assign;
            case llvm::Intrinsic::abs:
                return sdfg::data_flow::TaskletCode::int_abs;
            case llvm::Intrinsic::smax:
                return sdfg::data_flow::TaskletCode::int_smax;
            case llvm::Intrinsic::smin:
                return sdfg::data_flow::TaskletCode::int_smin;
            case llvm::Intrinsic::scmp:
                return sdfg::data_flow::TaskletCode::int_scmp;
            case llvm::Intrinsic::umax:
                return sdfg::data_flow::TaskletCode::int_umax;
            case llvm::Intrinsic::umin:
                return sdfg::data_flow::TaskletCode::int_umin;
            case llvm::Intrinsic::ucmp:
                return sdfg::data_flow::TaskletCode::int_ucmp;
            case llvm::Intrinsic::fmuladd:
                return sdfg::data_flow::TaskletCode::fp_fma;
            default:
                throw std::runtime_error("Intrinsic not mapped to a tasklet");
        }
    }

    static bool is_math(llvm::Intrinsic::ID iid) {
        switch (iid) {
            case llvm::Intrinsic::acos:
            case llvm::Intrinsic::asin:
            case llvm::Intrinsic::atan:
            case llvm::Intrinsic::ceil:
            case llvm::Intrinsic::copysign:
            case llvm::Intrinsic::cos:
            case llvm::Intrinsic::cosh:
            case llvm::Intrinsic::exp:
            case llvm::Intrinsic::exp10:
            case llvm::Intrinsic::exp2:
            case llvm::Intrinsic::fabs:
            case llvm::Intrinsic::floor:
            case llvm::Intrinsic::fma:
            case llvm::Intrinsic::ldexp:
            case llvm::Intrinsic::llrint:
            case llvm::Intrinsic::llround:
            case llvm::Intrinsic::log:
            case llvm::Intrinsic::log10:
            case llvm::Intrinsic::log2:
            case llvm::Intrinsic::lrint:
            case llvm::Intrinsic::lround:
            case llvm::Intrinsic::maximum:
            case llvm::Intrinsic::maxnum:
            case llvm::Intrinsic::minimum:
            case llvm::Intrinsic::minnum:
            case llvm::Intrinsic::nearbyint:
            case llvm::Intrinsic::pow:
            case llvm::Intrinsic::powi:
            case llvm::Intrinsic::rint:
            case llvm::Intrinsic::round:
            case llvm::Intrinsic::roundeven:
            case llvm::Intrinsic::sin:
            case llvm::Intrinsic::sinh:
            case llvm::Intrinsic::sqrt:
            case llvm::Intrinsic::tan:
            case llvm::Intrinsic::tanh:
            case llvm::Intrinsic::trunc:
                return true;
            default:
                return false;
        }
    }

    static sdfg::math::cmath::CMathFunction as_math_function(llvm::Intrinsic::ID iid) {
        switch (iid) {
            case llvm::Intrinsic::acos:
                return sdfg::math::cmath::CMathFunction::acos;
            case llvm::Intrinsic::asin:
                return sdfg::math::cmath::CMathFunction::asin;
            case llvm::Intrinsic::atan:
                return sdfg::math::cmath::CMathFunction::atan;
            case llvm::Intrinsic::ceil:
                return sdfg::math::cmath::CMathFunction::ceil;
            case llvm::Intrinsic::copysign:
                return sdfg::math::cmath::CMathFunction::copysign;
            case llvm::Intrinsic::cos:
                return sdfg::math::cmath::CMathFunction::cos;
            case llvm::Intrinsic::cosh:
                return sdfg::math::cmath::CMathFunction::cosh;
            case llvm::Intrinsic::exp:
                return sdfg::math::cmath::CMathFunction::exp;
            case llvm::Intrinsic::exp10:
                return sdfg::math::cmath::CMathFunction::exp10;
            case llvm::Intrinsic::exp2:
                return sdfg::math::cmath::CMathFunction::exp2;
            case llvm::Intrinsic::fabs:
                return sdfg::math::cmath::CMathFunction::fabs;
            case llvm::Intrinsic::floor:
                return sdfg::math::cmath::CMathFunction::floor;
            case llvm::Intrinsic::fma:
                return sdfg::math::cmath::CMathFunction::fma;
            case llvm::Intrinsic::ldexp:
                return sdfg::math::cmath::CMathFunction::ldexp;
            case llvm::Intrinsic::llrint:
                return sdfg::math::cmath::CMathFunction::llrint;
            case llvm::Intrinsic::llround:
                return sdfg::math::cmath::CMathFunction::llround;
            case llvm::Intrinsic::log:
                return sdfg::math::cmath::CMathFunction::log;
            case llvm::Intrinsic::log10:
                return sdfg::math::cmath::CMathFunction::log10;
            case llvm::Intrinsic::log2:
                return sdfg::math::cmath::CMathFunction::log2;
            case llvm::Intrinsic::lrint:
                return sdfg::math::cmath::CMathFunction::lrint;
            case llvm::Intrinsic::lround:
                return sdfg::math::cmath::CMathFunction::lround;
            case llvm::Intrinsic::maximum:
                return sdfg::math::cmath::CMathFunction::fmax;
            case llvm::Intrinsic::maxnum:
                return sdfg::math::cmath::CMathFunction::fmax;
            case llvm::Intrinsic::minimum:
                return sdfg::math::cmath::CMathFunction::fmin;
            case llvm::Intrinsic::minnum:
                return sdfg::math::cmath::CMathFunction::fmin;
            case llvm::Intrinsic::nearbyint:
                return sdfg::math::cmath::CMathFunction::nearbyint;
            case llvm::Intrinsic::pow:
                return sdfg::math::cmath::CMathFunction::pow;
            case llvm::Intrinsic::rint:
                return sdfg::math::cmath::CMathFunction::rint;
            case llvm::Intrinsic::round:
                return sdfg::math::cmath::CMathFunction::round;
            case llvm::Intrinsic::roundeven:
                return sdfg::math::cmath::CMathFunction::roundeven;
            case llvm::Intrinsic::sin:
                return sdfg::math::cmath::CMathFunction::sin;
            case llvm::Intrinsic::sinh:
                return sdfg::math::cmath::CMathFunction::sinh;
            case llvm::Intrinsic::sqrt:
                return sdfg::math::cmath::CMathFunction::sqrt;
            case llvm::Intrinsic::tan:
                return sdfg::math::cmath::CMathFunction::tan;
            case llvm::Intrinsic::tanh:
                return sdfg::math::cmath::CMathFunction::tanh;
            case llvm::Intrinsic::trunc:
                return sdfg::math::cmath::CMathFunction::trunc;
            default: {
                throw std::runtime_error("Intrinsic does not map to a math function");
            }
        }
    };

    sdfg::control_flow::State& visit_tasklet(
        const llvm::BasicBlock* block, const llvm::IntrinsicInst* instruction, sdfg::control_flow::State& current_state
    );

    sdfg::control_flow::State& visit_math(
        const llvm::BasicBlock* block, const llvm::IntrinsicInst* instruction, sdfg::control_flow::State& current_state
    );

    sdfg::control_flow::State& visit_memcpy(
        const llvm::BasicBlock* block, const llvm::IntrinsicInst* instruction, sdfg::control_flow::State& current_state
    );

    sdfg::control_flow::State& visit_memmove(
        const llvm::BasicBlock* block, const llvm::IntrinsicInst* instruction, sdfg::control_flow::State& current_state
    );

    sdfg::control_flow::State& visit_memset(
        const llvm::BasicBlock* block, const llvm::IntrinsicInst* instruction, sdfg::control_flow::State& current_state
    );

    sdfg::control_flow::State& visit_trap(
        const llvm::BasicBlock* block, const llvm::IntrinsicInst* instruction, sdfg::control_flow::State& current_state
    );

public:
    IntrinsicLifting(
        llvm::TargetLibraryInfo& TLI,
        const llvm::DataLayout& DL,
        const llvm::Function& function,
        sdfg::FunctionType target_type,
        sdfg::builder::SDFGBuilder& builder,
        std::map<const llvm::BasicBlock*, std::set<const sdfg::control_flow::State*>>& state_mapping,
        std::map<const sdfg::control_flow::State*, std::set<const llvm::BasicBlock*>>& pred_mapping,
        std::unordered_map<const llvm::Value*, std::string>& constants_mapping,
        std::unordered_map<const llvm::Type*, std::string> anonymous_types_mapping
    )
        : FunctionLifting(
              TLI,
              DL,
              function,
              target_type,
              builder,
              state_mapping,
              pred_mapping,
              constants_mapping,
              anonymous_types_mapping
          ) {}

    sdfg::control_flow::State& visit(
        const llvm::BasicBlock* block, const llvm::CallBase* instruction, sdfg::control_flow::State& current_state
    ) override;

    static bool is_supported(const llvm::IntrinsicInst* intrinsic) {
        auto iid = intrinsic->getIntrinsicID();
        switch (iid) {
            case llvm::Intrinsic::abs: {
                // Check if strict argument is set
                auto strict_arg = intrinsic->getArgOperand(1);
                if (auto const_int = llvm::dyn_cast<llvm::ConstantInt>(strict_arg)) {
                    if (const_int->getBitWidth() == 1) {
                        return !const_int->isZero();
                    }
                }
                return false;
            }
            case llvm::Intrinsic::acos:
                return true;
            case llvm::Intrinsic::annotation:
                return true;
            case llvm::Intrinsic::arithmetic_fence:
                return false;
            case llvm::Intrinsic::addressofreturnaddress:
                return false;
            case llvm::Intrinsic::adjust_trampoline:
                return false;
            case llvm::Intrinsic::allow_runtime_check:
                return false;
            case llvm::Intrinsic::allow_ubsan_check:
                return false;
            case llvm::Intrinsic::asan_check_memaccess:
                return false;
            case llvm::Intrinsic::asin:
                return true;
            case llvm::Intrinsic::assume:
                return true;
            case llvm::Intrinsic::atan:
                return true;
            case llvm::Intrinsic::bitreverse:
                return false;
            case llvm::Intrinsic::bswap:
                return false;
            case llvm::Intrinsic::call_preallocated_arg:
                return false;
            case llvm::Intrinsic::call_preallocated_setup:
                return false;
            case llvm::Intrinsic::call_preallocated_teardown:
                return false;
            case llvm::Intrinsic::callbr_landingpad:
                return false;
            case llvm::Intrinsic::canonicalize:
                return false;
            case llvm::Intrinsic::ceil:
                return true;
            case llvm::Intrinsic::clear_cache:
                return false;
            case llvm::Intrinsic::codeview_annotation:
                return false;
            case llvm::Intrinsic::convert_from_fp16:
                return false;
            case llvm::Intrinsic::convert_to_fp16:
                return false;
            case llvm::Intrinsic::copysign:
                return true;
            case llvm::Intrinsic::coro_align:
                return false;
            case llvm::Intrinsic::coro_alloc:
                return false;
            case llvm::Intrinsic::coro_alloca_alloc:
                return false;
            case llvm::Intrinsic::coro_alloca_free:
                return false;
            case llvm::Intrinsic::coro_alloca_get:
                return false;
            case llvm::Intrinsic::coro_async_context_alloc:
                return false;
            case llvm::Intrinsic::coro_async_context_dealloc:
                return false;
            case llvm::Intrinsic::coro_async_resume:
                return false;
            case llvm::Intrinsic::coro_async_size_replace:
                return false;
            case llvm::Intrinsic::coro_await_suspend_bool:
                return false;
            case llvm::Intrinsic::coro_await_suspend_handle:
                return false;
            case llvm::Intrinsic::coro_await_suspend_void:
                return false;
            case llvm::Intrinsic::coro_begin:
                return false;
            case llvm::Intrinsic::coro_destroy:
                return false;
            case llvm::Intrinsic::coro_done:
                return false;
            case llvm::Intrinsic::coro_end:
                return false;
            case llvm::Intrinsic::coro_end_async:
                return false;
            case llvm::Intrinsic::coro_end_results:
                return false;
            case llvm::Intrinsic::coro_frame:
                return false;
            case llvm::Intrinsic::coro_free:
                return false;
            case llvm::Intrinsic::coro_id:
                return false;
            case llvm::Intrinsic::coro_id_async:
                return false;
            case llvm::Intrinsic::coro_id_retcon:
                return false;
            case llvm::Intrinsic::coro_id_retcon_once:
                return false;
            case llvm::Intrinsic::coro_noop:
                return false;
            case llvm::Intrinsic::coro_prepare_async:
                return false;
            case llvm::Intrinsic::coro_prepare_retcon:
                return false;
            case llvm::Intrinsic::coro_promise:
                return false;
            case llvm::Intrinsic::coro_resume:
                return false;
            case llvm::Intrinsic::coro_save:
                return false;
            case llvm::Intrinsic::coro_size:
                return false;
            case llvm::Intrinsic::coro_subfn_addr:
                return false;
            case llvm::Intrinsic::coro_suspend:
                return false;
            case llvm::Intrinsic::coro_suspend_async:
                return false;
            case llvm::Intrinsic::coro_suspend_retcon:
                return false;
            case llvm::Intrinsic::cos:
                return true;
            case llvm::Intrinsic::cosh:
                return true;
            case llvm::Intrinsic::ctlz:
                return false;
            case llvm::Intrinsic::ctpop:
                return false;
            case llvm::Intrinsic::cttz:
                return false;
            case llvm::Intrinsic::dbg_assign:
                return true;
            case llvm::Intrinsic::dbg_declare:
                return true;
            case llvm::Intrinsic::dbg_label:
                return true;
            case llvm::Intrinsic::dbg_value:
                return true;
            case llvm::Intrinsic::debugtrap:
                return false;
            case llvm::Intrinsic::donothing:
                return true;
            case llvm::Intrinsic::eh_dwarf_cfa:
                return false;
            case llvm::Intrinsic::eh_exceptioncode:
                return false;
            case llvm::Intrinsic::eh_exceptionpointer:
                return false;
            case llvm::Intrinsic::eh_recoverfp:
                return false;
            case llvm::Intrinsic::eh_return_i32:
                return false;
            case llvm::Intrinsic::eh_return_i64:
                return false;
            case llvm::Intrinsic::eh_sjlj_callsite:
                return false;
            case llvm::Intrinsic::eh_sjlj_functioncontext:
                return false;
            case llvm::Intrinsic::eh_sjlj_longjmp:
                return false;
            case llvm::Intrinsic::eh_sjlj_lsda:
                return false;
            case llvm::Intrinsic::eh_sjlj_setjmp:
                return false;
            case llvm::Intrinsic::eh_sjlj_setup_dispatch:
                return false;
            case llvm::Intrinsic::eh_typeid_for:
                return false;
            case llvm::Intrinsic::eh_unwind_init:
                return false;
            case llvm::Intrinsic::exp:
                return true;
            case llvm::Intrinsic::exp10:
                return true;
            case llvm::Intrinsic::exp2:
                return true;
            case llvm::Intrinsic::expect:
                return true;
            case llvm::Intrinsic::expect_with_probability:
                return true;
            case llvm::Intrinsic::experimental_constrained_acos:
                return false;
            case llvm::Intrinsic::experimental_constrained_asin:
                return false;
            case llvm::Intrinsic::experimental_constrained_atan:
                return false;
            case llvm::Intrinsic::experimental_constrained_ceil:
                return false;
            case llvm::Intrinsic::experimental_constrained_cos:
                return false;
            case llvm::Intrinsic::experimental_constrained_cosh:
                return false;
            case llvm::Intrinsic::experimental_constrained_exp:
                return false;
            case llvm::Intrinsic::experimental_constrained_exp2:
                return false;
            case llvm::Intrinsic::experimental_constrained_fadd:
                return false;
            case llvm::Intrinsic::experimental_constrained_fcmp:
                return false;
            case llvm::Intrinsic::experimental_constrained_fcmps:
                return false;
            case llvm::Intrinsic::experimental_constrained_fdiv:
                return false;
            case llvm::Intrinsic::experimental_constrained_floor:
                return false;
            case llvm::Intrinsic::experimental_constrained_fma:
                return false;
            case llvm::Intrinsic::experimental_constrained_fmul:
                return false;
            case llvm::Intrinsic::experimental_constrained_fmuladd:
                return false;
            case llvm::Intrinsic::experimental_constrained_fpext:
                return false;
            case llvm::Intrinsic::experimental_constrained_fptosi:
                return false;
            case llvm::Intrinsic::experimental_constrained_fptoui:
                return false;
            case llvm::Intrinsic::experimental_constrained_fptrunc:
                return false;
            case llvm::Intrinsic::experimental_constrained_frem:
                return false;
            case llvm::Intrinsic::experimental_constrained_fsub:
                return false;
            case llvm::Intrinsic::experimental_constrained_ldexp:
                return false;
            case llvm::Intrinsic::experimental_constrained_llrint:
                return false;
            case llvm::Intrinsic::experimental_constrained_llround:
                return false;
            case llvm::Intrinsic::experimental_constrained_log:
                return false;
            case llvm::Intrinsic::experimental_constrained_log10:
                return false;
            case llvm::Intrinsic::experimental_constrained_log2:
                return false;
            case llvm::Intrinsic::experimental_constrained_lrint:
                return false;
            case llvm::Intrinsic::experimental_constrained_lround:
                return false;
            case llvm::Intrinsic::experimental_constrained_maximum:
                return false;
            case llvm::Intrinsic::experimental_constrained_maxnum:
                return false;
            case llvm::Intrinsic::experimental_constrained_minimum:
                return false;
            case llvm::Intrinsic::experimental_constrained_minnum:
                return false;
            case llvm::Intrinsic::experimental_constrained_nearbyint:
                return false;
            case llvm::Intrinsic::experimental_constrained_pow:
                return false;
            case llvm::Intrinsic::experimental_constrained_powi:
                return false;
            case llvm::Intrinsic::experimental_constrained_rint:
                return false;
            case llvm::Intrinsic::experimental_constrained_round:
                return false;
            case llvm::Intrinsic::experimental_constrained_roundeven:
                return false;
            case llvm::Intrinsic::experimental_constrained_sin:
                return false;
            case llvm::Intrinsic::experimental_constrained_sinh:
                return false;
            case llvm::Intrinsic::experimental_constrained_sitofp:
                return false;
            case llvm::Intrinsic::experimental_constrained_sqrt:
                return false;
            case llvm::Intrinsic::experimental_constrained_tan:
                return false;
            case llvm::Intrinsic::experimental_constrained_tanh:
                return false;
            case llvm::Intrinsic::experimental_constrained_trunc:
                return false;
            case llvm::Intrinsic::experimental_constrained_uitofp:
                return false;
            case llvm::Intrinsic::experimental_convergence_anchor:
                return false;
            case llvm::Intrinsic::experimental_convergence_entry:
                return false;
            case llvm::Intrinsic::experimental_convergence_loop:
                return false;
            case llvm::Intrinsic::experimental_cttz_elts:
                return false;
            case llvm::Intrinsic::experimental_deoptimize:
                return false;
            case llvm::Intrinsic::experimental_gc_get_pointer_base:
                return false;
            case llvm::Intrinsic::experimental_gc_get_pointer_offset:
                return false;
            case llvm::Intrinsic::experimental_gc_relocate:
                return false;
            case llvm::Intrinsic::experimental_gc_result:
                return false;
            case llvm::Intrinsic::experimental_gc_statepoint:
                return false;
            case llvm::Intrinsic::experimental_get_vector_length:
                return false;
            case llvm::Intrinsic::experimental_guard:
                return false;
            case llvm::Intrinsic::experimental_noalias_scope_decl:
                return true;
            case llvm::Intrinsic::experimental_patchpoint:
                return false;
            case llvm::Intrinsic::experimental_patchpoint_void:
                return false;
            case llvm::Intrinsic::experimental_stackmap:
                return false;
            case llvm::Intrinsic::experimental_stepvector:
                return false;
            case llvm::Intrinsic::experimental_vector_compress:
                return false;
            case llvm::Intrinsic::experimental_vector_histogram_add:
                return false;
            case llvm::Intrinsic::experimental_vector_partial_reduce_add:
                return false;
            case llvm::Intrinsic::experimental_vp_reverse:
                return false;
            case llvm::Intrinsic::experimental_vp_splat:
                return false;
            case llvm::Intrinsic::experimental_vp_splice:
                return false;
            case llvm::Intrinsic::experimental_vp_strided_load:
                return false;
            case llvm::Intrinsic::experimental_vp_strided_store:
                return false;
            case llvm::Intrinsic::experimental_widenable_condition:
                return false;
            case llvm::Intrinsic::fabs:
                return true;
            case llvm::Intrinsic::floor:
                return true;
            case llvm::Intrinsic::fma:
                return true;
            case llvm::Intrinsic::fmuladd:
                return true;
            case llvm::Intrinsic::fptosi_sat:
                return false;
            case llvm::Intrinsic::fptoui_sat:
                return false;
            case llvm::Intrinsic::fptrunc_round:
                return false;
            case llvm::Intrinsic::frameaddress:
                return false;
            case llvm::Intrinsic::frexp:
                return false;
            case llvm::Intrinsic::fshl:
                return false;
            case llvm::Intrinsic::fshr:
                return false;
            case llvm::Intrinsic::gcread:
                return false;
            case llvm::Intrinsic::gcroot:
                return false;
            case llvm::Intrinsic::gcwrite:
                return false;
            case llvm::Intrinsic::get_active_lane_mask:
                return false;
            case llvm::Intrinsic::get_dynamic_area_offset:
                return false;
            case llvm::Intrinsic::get_fpenv:
                return false;
            case llvm::Intrinsic::get_fpmode:
                return false;
            case llvm::Intrinsic::get_rounding:
                return false;
            case llvm::Intrinsic::hwasan_check_memaccess:
                return false;
            case llvm::Intrinsic::hwasan_check_memaccess_fixedshadow:
                return false;
            case llvm::Intrinsic::hwasan_check_memaccess_shortgranules:
                return false;
            case llvm::Intrinsic::hwasan_check_memaccess_shortgranules_fixedshadow:
                return false;
            case llvm::Intrinsic::icall_branch_funnel:
                return false;
            case llvm::Intrinsic::init_trampoline:
                return false;
            case llvm::Intrinsic::instrprof_callsite:
                return false;
            case llvm::Intrinsic::instrprof_cover:
                return false;
            case llvm::Intrinsic::instrprof_increment:
                return false;
            case llvm::Intrinsic::instrprof_increment_step:
                return false;
            case llvm::Intrinsic::instrprof_mcdc_parameters:
                return false;
            case llvm::Intrinsic::instrprof_mcdc_tvbitmap_update:
                return false;
            case llvm::Intrinsic::instrprof_timestamp:
                return false;
            case llvm::Intrinsic::instrprof_value_profile:
                return false;
            case llvm::Intrinsic::invariant_end:
                return true;
            case llvm::Intrinsic::invariant_start:
                return true;
            case llvm::Intrinsic::is_constant:
                return false;
            case llvm::Intrinsic::is_fpclass:
                return false;
            case llvm::Intrinsic::launder_invariant_group:
                return false;
            case llvm::Intrinsic::ldexp:
                return true;
            case llvm::Intrinsic::lifetime_end:
                return true;
            case llvm::Intrinsic::lifetime_start:
                return true;
            case llvm::Intrinsic::llrint:
                return true;
            case llvm::Intrinsic::llround:
                return true;
            case llvm::Intrinsic::load_relative:
                return false;
            case llvm::Intrinsic::localaddress:
                return false;
            case llvm::Intrinsic::localescape:
                return false;
            case llvm::Intrinsic::localrecover:
                return false;
            case llvm::Intrinsic::log:
                return true;
            case llvm::Intrinsic::log10:
                return true;
            case llvm::Intrinsic::log2:
                return true;
            case llvm::Intrinsic::loop_decrement:
                return false;
            case llvm::Intrinsic::loop_decrement_reg:
                return false;
            case llvm::Intrinsic::lrint:
                return true;
            case llvm::Intrinsic::lround:
                return true;
            case llvm::Intrinsic::masked_compressstore:
                return false;
            case llvm::Intrinsic::masked_expandload:
                return false;
            case llvm::Intrinsic::masked_gather:
                return false;
            case llvm::Intrinsic::masked_load:
                return false;
            case llvm::Intrinsic::masked_scatter:
                return false;
            case llvm::Intrinsic::masked_store:
                return false;
            case llvm::Intrinsic::matrix_column_major_load:
                return false;
            case llvm::Intrinsic::matrix_column_major_store:
                return false;
            case llvm::Intrinsic::matrix_multiply:
                return false;
            case llvm::Intrinsic::matrix_transpose:
                return false;
            case llvm::Intrinsic::maximum:
                return true;
            case llvm::Intrinsic::maxnum:
                return true;
            case llvm::Intrinsic::memcpy:
                return true;
            case llvm::Intrinsic::memcpy_element_unordered_atomic:
                return false;
            case llvm::Intrinsic::memcpy_inline:
                return false;
            case llvm::Intrinsic::memmove:
                return true;
            case llvm::Intrinsic::memmove_element_unordered_atomic:
                return false;
            case llvm::Intrinsic::memset:
                return true;
            case llvm::Intrinsic::memset_element_unordered_atomic:
                return false;
            case llvm::Intrinsic::memset_inline:
                return false;
            case llvm::Intrinsic::minimum:
                return true;
            case llvm::Intrinsic::minnum:
                return true;
            case llvm::Intrinsic::nearbyint:
                return true;
            case llvm::Intrinsic::objc_arc_annotation_bottomup_bbend:
                return false;
            case llvm::Intrinsic::objc_arc_annotation_bottomup_bbstart:
                return false;
            case llvm::Intrinsic::objc_arc_annotation_topdown_bbend:
                return false;
            case llvm::Intrinsic::objc_arc_annotation_topdown_bbstart:
                return false;
            case llvm::Intrinsic::objc_autorelease:
                return false;
            case llvm::Intrinsic::objc_autoreleasePoolPop:
                return false;
            case llvm::Intrinsic::objc_autoreleasePoolPush:
                return false;
            case llvm::Intrinsic::objc_autoreleaseReturnValue:
                return false;
            case llvm::Intrinsic::objc_clang_arc_noop_use:
                return false;
            case llvm::Intrinsic::objc_clang_arc_use:
                return false;
            case llvm::Intrinsic::objc_copyWeak:
                return false;
            case llvm::Intrinsic::objc_destroyWeak:
                return false;
            case llvm::Intrinsic::objc_initWeak:
                return false;
            case llvm::Intrinsic::objc_loadWeak:
                return false;
            case llvm::Intrinsic::objc_loadWeakRetained:
                return false;
            case llvm::Intrinsic::objc_moveWeak:
                return false;
            case llvm::Intrinsic::objc_release:
                return false;
            case llvm::Intrinsic::objc_retain:
                return false;
            case llvm::Intrinsic::objc_retain_autorelease:
                return false;
            case llvm::Intrinsic::objc_retainAutorelease:
                return false;
            case llvm::Intrinsic::objc_retainAutoreleaseReturnValue:
                return false;
            case llvm::Intrinsic::objc_retainAutoreleasedReturnValue:
                return false;
            case llvm::Intrinsic::objc_retainBlock:
                return false;
            case llvm::Intrinsic::objc_retainedObject:
                return false;
            case llvm::Intrinsic::objc_storeStrong:
                return false;
            case llvm::Intrinsic::objc_storeWeak:
                return false;
            case llvm::Intrinsic::objc_sync_enter:
                return false;
            case llvm::Intrinsic::objc_sync_exit:
                return false;
            case llvm::Intrinsic::objc_unretainedObject:
                return false;
            case llvm::Intrinsic::objc_unretainedPointer:
                return false;
            case llvm::Intrinsic::objc_unsafeClaimAutoreleasedReturnValue:
                return false;
            case llvm::Intrinsic::objectsize:
                return false;
            case llvm::Intrinsic::pcmarker:
                return false;
            case llvm::Intrinsic::pow:
                return true;
            case llvm::Intrinsic::powi:
                return true;
            case llvm::Intrinsic::prefetch:
                return false;
            case llvm::Intrinsic::preserve_array_access_index:
                return false;
            case llvm::Intrinsic::preserve_static_offset:
                return false;
            case llvm::Intrinsic::preserve_struct_access_index:
                return false;
            case llvm::Intrinsic::preserve_union_access_index:
                return false;
            case llvm::Intrinsic::pseudoprobe:
                return false;
            case llvm::Intrinsic::ptr_annotation:
                return true;
            case llvm::Intrinsic::ptrauth_auth:
                return false;
            case llvm::Intrinsic::ptrauth_blend:
                return false;
            case llvm::Intrinsic::ptrauth_resign:
                return false;
            case llvm::Intrinsic::ptrauth_sign:
                return false;
            case llvm::Intrinsic::ptrauth_sign_generic:
                return false;
            case llvm::Intrinsic::ptrauth_strip:
                return false;
            case llvm::Intrinsic::ptrmask:
                return false;
            case llvm::Intrinsic::public_type_test:
                return false;
            case llvm::Intrinsic::read_register:
                return false;
            case llvm::Intrinsic::read_volatile_register:
                return false;
            case llvm::Intrinsic::readcyclecounter:
                return false;
            case llvm::Intrinsic::readsteadycounter:
                return false;
            case llvm::Intrinsic::reset_fpenv:
                return false;
            case llvm::Intrinsic::reset_fpmode:
                return false;
            case llvm::Intrinsic::returnaddress:
                return false;
            case llvm::Intrinsic::rint:
                return true;
            case llvm::Intrinsic::round:
                return true;
            case llvm::Intrinsic::roundeven:
                return true;
            case llvm::Intrinsic::sadd_sat:
                return false;
            case llvm::Intrinsic::sadd_with_overflow:
                return false;
            case llvm::Intrinsic::scmp:
                return true;
            case llvm::Intrinsic::sdiv_fix:
                return false;
            case llvm::Intrinsic::sdiv_fix_sat:
                return false;
            case llvm::Intrinsic::seh_scope_begin:
                return false;
            case llvm::Intrinsic::seh_scope_end:
                return false;
            case llvm::Intrinsic::seh_try_begin:
                return false;
            case llvm::Intrinsic::seh_try_end:
                return false;
            case llvm::Intrinsic::set_fpenv:
                return false;
            case llvm::Intrinsic::set_fpmode:
                return false;
            case llvm::Intrinsic::set_loop_iterations:
                return false;
            case llvm::Intrinsic::set_rounding:
                return false;
            case llvm::Intrinsic::sideeffect:
                return false;
            case llvm::Intrinsic::sin:
                return true;
            case llvm::Intrinsic::sinh:
                return true;
            case llvm::Intrinsic::smax:
                return true;
            case llvm::Intrinsic::smin:
                return true;
            case llvm::Intrinsic::smul_fix:
                return false;
            case llvm::Intrinsic::smul_fix_sat:
                return false;
            case llvm::Intrinsic::smul_with_overflow:
                return false;
            case llvm::Intrinsic::sponentry:
                return false;
            case llvm::Intrinsic::sqrt:
                return true;
            case llvm::Intrinsic::ssa_copy:
                return false;
            case llvm::Intrinsic::sshl_sat:
                return false;
            case llvm::Intrinsic::ssub_sat:
                return false;
            case llvm::Intrinsic::ssub_with_overflow:
                return false;
            case llvm::Intrinsic::stackguard:
                return false;
            case llvm::Intrinsic::stackprotector:
                return false;
            case llvm::Intrinsic::stackrestore:
                return false;
            case llvm::Intrinsic::stacksave:
                return false;
            case llvm::Intrinsic::start_loop_iterations:
                return false;
            case llvm::Intrinsic::strip_invariant_group:
                return false;
            case llvm::Intrinsic::swift_async_context_addr:
                return false;
            case llvm::Intrinsic::tan:
                return true;
            case llvm::Intrinsic::tanh:
                return true;
            case llvm::Intrinsic::test_set_loop_iterations:
                return false;
            case llvm::Intrinsic::test_start_loop_iterations:
                return false;
            case llvm::Intrinsic::thread_pointer:
                return false;
            case llvm::Intrinsic::threadlocal_address:
                return false;
            case llvm::Intrinsic::trap:
                return true;
            case llvm::Intrinsic::trunc:
                return true;
            case llvm::Intrinsic::type_checked_load:
                return false;
            case llvm::Intrinsic::type_checked_load_relative:
                return false;
            case llvm::Intrinsic::type_test:
                return false;
            case llvm::Intrinsic::uadd_sat:
                return false;
            case llvm::Intrinsic::uadd_with_overflow:
                return false;
            case llvm::Intrinsic::ubsantrap:
                return false;
            case llvm::Intrinsic::ucmp:
                return true;
            case llvm::Intrinsic::udiv_fix:
                return false;
            case llvm::Intrinsic::udiv_fix_sat:
                return false;
            case llvm::Intrinsic::umax:
                return true;
            case llvm::Intrinsic::umin:
                return true;
            case llvm::Intrinsic::umul_fix:
                return false;
            case llvm::Intrinsic::umul_fix_sat:
                return false;
            case llvm::Intrinsic::umul_with_overflow:
                return false;
            case llvm::Intrinsic::ushl_sat:
                return false;
            case llvm::Intrinsic::usub_sat:
                return false;
            case llvm::Intrinsic::usub_with_overflow:
                return false;
            case llvm::Intrinsic::vacopy:
                return false;
            case llvm::Intrinsic::vaend:
                return false;
            case llvm::Intrinsic::vastart:
                return false;
            case llvm::Intrinsic::var_annotation:
                return true;
            case llvm::Intrinsic::vector_deinterleave2:
                return false;
            case llvm::Intrinsic::vector_extract:
                return false;
            case llvm::Intrinsic::vector_insert:
                return false;
            case llvm::Intrinsic::vector_interleave2:
                return false;
            case llvm::Intrinsic::vector_reduce_add:
                return false;
            case llvm::Intrinsic::vector_reduce_and:
                return false;
            case llvm::Intrinsic::vector_reduce_fadd:
                return false;
            case llvm::Intrinsic::vector_reduce_fmax:
                return false;
            case llvm::Intrinsic::vector_reduce_fmaximum:
                return false;
            case llvm::Intrinsic::vector_reduce_fmin:
                return false;
            case llvm::Intrinsic::vector_reduce_fminimum:
                return false;
            case llvm::Intrinsic::vector_reduce_fmul:
                return false;
            case llvm::Intrinsic::vector_reduce_mul:
                return false;
            case llvm::Intrinsic::vector_reduce_or:
                return false;
            case llvm::Intrinsic::vector_reduce_smax:
                return false;
            case llvm::Intrinsic::vector_reduce_smin:
                return false;
            case llvm::Intrinsic::vector_reduce_umax:
                return false;
            case llvm::Intrinsic::vector_reduce_umin:
                return false;
            case llvm::Intrinsic::vector_reduce_xor:
                return false;
            case llvm::Intrinsic::vector_reverse:
                return false;
            case llvm::Intrinsic::vector_splice:
                return false;
            case llvm::Intrinsic::vp_abs:
                return false;
            case llvm::Intrinsic::vp_add:
                return false;
            case llvm::Intrinsic::vp_and:
                return false;
            case llvm::Intrinsic::vp_ashr:
                return false;
            case llvm::Intrinsic::vp_bitreverse:
                return false;
            case llvm::Intrinsic::vp_bswap:
                return false;
            case llvm::Intrinsic::vp_ceil:
                return false;
            case llvm::Intrinsic::vp_copysign:
                return false;
            case llvm::Intrinsic::vp_ctlz:
                return false;
            case llvm::Intrinsic::vp_ctpop:
                return false;
            case llvm::Intrinsic::vp_cttz:
                return false;
            case llvm::Intrinsic::vp_cttz_elts:
                return false;
            case llvm::Intrinsic::vp_fabs:
                return false;
            case llvm::Intrinsic::vp_fadd:
                return false;
            case llvm::Intrinsic::vp_fcmp:
                return false;
            case llvm::Intrinsic::vp_fdiv:
                return false;
            case llvm::Intrinsic::vp_floor:
                return false;
            case llvm::Intrinsic::vp_fma:
                return false;
            case llvm::Intrinsic::vp_fmul:
                return false;
            case llvm::Intrinsic::vp_fmuladd:
                return false;
            case llvm::Intrinsic::vp_fneg:
                return false;
            case llvm::Intrinsic::vp_fpext:
                return false;
            case llvm::Intrinsic::vp_fptosi:
                return false;
            case llvm::Intrinsic::vp_fptoui:
                return false;
            case llvm::Intrinsic::vp_fptrunc:
                return false;
            case llvm::Intrinsic::vp_frem:
                return false;
            case llvm::Intrinsic::vp_fshl:
                return false;
            case llvm::Intrinsic::vp_fshr:
                return false;
            case llvm::Intrinsic::vp_fsub:
                return false;
            case llvm::Intrinsic::vp_gather:
                return false;
            case llvm::Intrinsic::vp_icmp:
                return false;
            case llvm::Intrinsic::vp_inttoptr:
                return false;
            case llvm::Intrinsic::vp_is_fpclass:
                return false;
            case llvm::Intrinsic::vp_llrint:
                return false;
            case llvm::Intrinsic::vp_load:
                return false;
            case llvm::Intrinsic::vp_lrint:
                return false;
            case llvm::Intrinsic::vp_lshr:
                return false;
            case llvm::Intrinsic::vp_maximum:
                return false;
            case llvm::Intrinsic::vp_maxnum:
                return false;
            case llvm::Intrinsic::vp_merge:
                return false;
            case llvm::Intrinsic::vp_minimum:
                return false;
            case llvm::Intrinsic::vp_minnum:
                return false;
            case llvm::Intrinsic::vp_mul:
                return false;
            case llvm::Intrinsic::vp_nearbyint:
                return false;
            case llvm::Intrinsic::vp_or:
                return false;
            case llvm::Intrinsic::vp_ptrtoint:
                return false;
            case llvm::Intrinsic::vp_reduce_add:
                return false;
            case llvm::Intrinsic::vp_reduce_and:
                return false;
            case llvm::Intrinsic::vp_reduce_fadd:
                return false;
            case llvm::Intrinsic::vp_reduce_fmax:
                return false;
            case llvm::Intrinsic::vp_reduce_fmaximum:
                return false;
            case llvm::Intrinsic::vp_reduce_fmin:
                return false;
            case llvm::Intrinsic::vp_reduce_fminimum:
                return false;
            case llvm::Intrinsic::vp_reduce_fmul:
                return false;
            case llvm::Intrinsic::vp_reduce_mul:
                return false;
            case llvm::Intrinsic::vp_reduce_or:
                return false;
            case llvm::Intrinsic::vp_reduce_smax:
                return false;
            case llvm::Intrinsic::vp_reduce_smin:
                return false;
            case llvm::Intrinsic::vp_reduce_umax:
                return false;
            case llvm::Intrinsic::vp_reduce_umin:
                return false;
            case llvm::Intrinsic::vp_reduce_xor:
                return false;
            case llvm::Intrinsic::vp_rint:
                return false;
            case llvm::Intrinsic::vp_round:
                return false;
            case llvm::Intrinsic::vp_roundeven:
                return false;
            case llvm::Intrinsic::vp_roundtozero:
                return false;
            case llvm::Intrinsic::vp_sadd_sat:
                return false;
            case llvm::Intrinsic::vp_scatter:
                return false;
            case llvm::Intrinsic::vp_sdiv:
                return false;
            case llvm::Intrinsic::vp_select:
                return false;
            case llvm::Intrinsic::vp_sext:
                return false;
            case llvm::Intrinsic::vp_shl:
                return false;
            case llvm::Intrinsic::vp_sitofp:
                return false;
            case llvm::Intrinsic::vp_smax:
                return false;
            case llvm::Intrinsic::vp_smin:
                return false;
            case llvm::Intrinsic::vp_sqrt:
                return false;
            case llvm::Intrinsic::vp_srem:
                return false;
            case llvm::Intrinsic::vp_ssub_sat:
                return false;
            case llvm::Intrinsic::vp_store:
                return false;
            case llvm::Intrinsic::vp_sub:
                return false;
            case llvm::Intrinsic::vp_trunc:
                return false;
            case llvm::Intrinsic::vp_uadd_sat:
                return false;
            case llvm::Intrinsic::vp_udiv:
                return false;
            case llvm::Intrinsic::vp_uitofp:
                return false;
            case llvm::Intrinsic::vp_umax:
                return false;
            case llvm::Intrinsic::vp_umin:
                return false;
            case llvm::Intrinsic::vp_urem:
                return false;
            case llvm::Intrinsic::vp_usub_sat:
                return false;
            case llvm::Intrinsic::vp_xor:
                return false;
            case llvm::Intrinsic::vp_zext:
                return false;
            case llvm::Intrinsic::vscale:
                return false;
            case llvm::Intrinsic::write_register:
                return false;
            case llvm::Intrinsic::xray_customevent:
                return false;
            case llvm::Intrinsic::xray_typedevent:
                return false;
        }
        throw std::runtime_error("This point shall not be reached");
    };
};

} // namespace lifting
} // namespace docc
