"""CUDA offload-dispatcher test suite.

A thin binding of the backend-agnostic scenarios in
``_gpu_offload_dispatcher_impl`` to the CUDA backend (32-lane warps, NVIDIA
device storage, ``cuda_offload`` schedules, ``*.cu`` codegen).  Every test is
generated by :func:`register` and carries the module-level ``cuda`` marker.
"""

import pytest

import _gpu_offload_dispatcher_impl as gpu

pytestmark = pytest.mark.cuda()

gpu.register(globals(), gpu.CUDA_BACKEND)
