"""ROCm offload-dispatcher test suite.

A thin binding of the backend-agnostic scenarios in
``_gpu_offload_dispatcher_impl`` to the ROCm backend (64-lane wavefronts, AMD
device storage, ``rocm_offload`` schedules, ``*rocm.cpp`` codegen).  Every test
is generated by :func:`register` and carries the module-level ``rocm`` marker.
"""

import pytest

import _gpu_offload_dispatcher_impl as gpu

pytestmark = pytest.mark.rocm()

gpu.register(globals(), gpu.ROCM_BACKEND)
